<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            ['name' => 'Bachelor of Science in Criminology'],
            ['name' => 'Bachelor of Science in Agriculture & Agriculture Related Fields'],
            ['name' => 'Bachelor of Arts in Islamic Studies'],
            ['name' => 'Bachelor of Elementary Education'],
            ['name' => 'Bachelor of Science in Naval Architecture'],
            ['name' => 'Bachelor of Science in Culture and the Arts'],
            ['name' => 'Bachelor of Science in Physics'],
            ['name' => 'Bachelor of Science in Applied Mathematics'],
            ['name' => 'Bachelor of Science in Mathematics'],
            ['name' => 'Bachelor of Science in Applied Statistics'],
            ['name' => 'Bachelor of Science in Statistics'],
            ['name' => 'Bachelor of Science in Biochemistry'],
            ['name' => 'Bachelor of Science in Biology'],
            ['name' => 'Bachelor of Science in Botany'],
            ['name' => 'Bachelor of Science in Chemistry'],
            ['name' => 'Bachelor of Science in Environmental Science'],
            ['name' => 'Bachelor of Science in Geology'],
            ['name' => 'Bachelor of Science in Human Biology'],
            ['name' => 'Bachelor of Science in Marine Biology'],
            ['name' => 'Bachelor of Science in Marine Science'],
            ['name' => 'Bachelor of Science in Meteorology'],
            ['name' => 'Bachelor of Science in Molecular Biology and Biotechnology'],
            ['name' => 'Bachelor of Science in Computer Science'],
            ['name' => 'Bachelor of Science in Cyber Security'],
            ['name' => 'Bachelor of Science in Entertainment and Multimedia Computing'],
            ['name' => 'Bachelor of Science in  Game Development and Animation'],
            ['name' => 'Bachelor of Science in Information Technology'],
            ['name' => 'Bachelor of Science in Library and Information Science'],
            ['name' => 'Bachelor of Science in Agricultural & Biosystems Engineering'],
            ['name' => 'Bachelor of Science in Ceramic Engineering'],
            ['name' => 'Bachelor of Science in Chemical Engineering'],
            ['name' => 'Bachelor of Science in Civil Engineering'],
            ['name' => 'Bachelor of Science in Computer Engineering'],
            ['name' => 'Bachelor of Science in Electrical Engineering'],
            ['name' => 'Bachelor of Science in Electronics Engineering'],
            ['name' => 'Bachelor of Science in Electronics and Communications Engineering'],
            ['name' => 'Bachelor of Science in Food Engineering'],
            ['name' => 'Bachelor of Science in Geodetic Engineering'],
            ['name' => 'Bachelor of Science in Industrial Engineering'],
            ['name' => 'Bachelor of Science in Manufacturing Engineering'],
            ['name' => 'Bachelor of Science in Production Engineering'],
            ['name' => 'Bachelor of Science in Materials Engineering'],
            ['name' => 'Bachelor of Science in Mechanical Engineering'],
            ['name' => 'Bachelor of Science in Mechatronics Engineering'],
            ['name' => 'Bachelor of Science in Metallurgical Engineering'],
            ['name' => 'Bachelor of Science in Mining Engineering'],
            ['name' => 'Bachelor of Science in Petrolium Engineering'],
            ['name' => 'Bachelor of Science in Robotics Engineering'],
            ['name' => 'Bachelor of Science in Sanitary Engineering'],
            ['name' => 'Bachelor of Science in Structural Engineering'],
            ['name' => 'Bachelor of Science in Aircraft Maintenance Technology'],
            ['name' => 'Bachelor of Science in Aviation Technology and Related'],
            ['name' => 'Bachelor of Science in Engineering Technology'],
            ['name' => 'Bachelor of Science in Industrial Technology'],
            ['name' => 'Bachelor of Science in Mechatronics Engineering Technology'],
            ['name' => 'Bachelor of Science in Architecture'],
            ['name' => 'Bachelor of Science in Fine Arts'],
            ['name' => 'Bachelor of Science in Interior Design'],
            ['name' => 'Bachelor of Science in Landscape Architecture'],
            ['name' => 'Bachelor of Science in Environmental Planning'],
            ['name' => 'Bachelor of Science in Accountancy'],
            ['name' => 'Bachelor of Science in Business Analytics'],
            ['name' => 'Bachelor of Science in Business Administration major in Business Analytics'],
            ['name' => 'Bachelor of Science in Hospitality Management'],
            ['name' => 'Bachelor of Science in Hotel and Restaurant Management'],
            ['name' => 'Bachelor of Science in Tourism Management'],
            ['name' => 'Bachelor of Science in Tourism'],
            ['name' => 'Doctor of Dental Medicine'],
            ['name' => 'Doctor of Optometry'],
            ['name' => 'Bachelor of Science in Medical Technology'],
            ['name' => 'Bachelor of Science in Medical Laboratory Science'],
            ['name' => 'Bachelor of Science in Midwifery'],
            ['name' => 'Bachelor of Science in Nursing'],
            ['name' => 'Bachelor of Science in Nutrition and Dietetics'],
            ['name' => 'Bachelor of Science in Occupational Therapy'],
            ['name' => 'Bachelor of Science in Pharmacy'],
            ['name' => 'Bachelor of Science in Physical Therapy'],
            ['name' => 'Bachelor of Science in Radiologic Technology'],
            ['name' => 'Bachelor of Science in Respiratory Therapy'],
            ['name' => 'Bachelor of Science in Speech Language Pathology'],
            ['name' => 'Bachelor of Science in Naval Architecture and Marine Engineering'],
            ['name' => 'Bachelor of Science in Public Health'],
            ['name' => 'Bachelor of Science in Volcano and Seismology Related Fields'],
            ['name' => 'Bachelor of Science in Community Development'],
            ['name' => 'Bachelor of Science in Human Services (Guidance and Counselling)'],
            ['name' => 'Bachelor of Science in Indigenous Peoples Studies/Education'],
            ['name' => 'Bachelor of Science in Peace Studies/Education'],
            ['name' => 'Bachelor of Science in Psychology'],
            ['name' => 'Bachelor of Science in Social Work'],
            ['name' => 'Bachelor of Secondary Education major in Science'],
            ['name' => 'Bachelor of Secondary Education major in Mathematics'],
            ['name' => 'Bachelor of Secondary Education major in Culture and Arts'],
            ['name' => 'Bachelor of Early Childhood Education'],
            ['name' => 'Bachelor of Special Needs Education'],
            ['name' => 'Bachelor of Science in Sports and Exercise Science'],
            ['name' => 'Bachelor of Science in Agribusiness'],
            ['name' => 'Bachelor of Science in Agro-Forestry'],
            ['name' => 'Bachelor of Science in Data Science and Analytics'],
            ['name' => 'Bachelor of Science in Disaster Risk Management/Climate Change'],
            ['name' => 'Renewable/Sustainable Energy'],
            ['name' => 'Bachelor of Science in Fisheries'],
        ];

        foreach ($courses as $c) {
            Course::create($c);
        }
    }
}
