<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolSeeder extends Seeder
{
    public function run(): void
    {
        $schools = [
            ['name' => 'ST. ALEXIUS COLLEGE, INC.'],
            ['name' => 'EDENTON MISSION COLLEGE, INC.'],
            ['name' => 'GENSANTOS FOUNDATION COLLEGE, INC.'],
            ['name' => 'HOLY TRINITY COLLEGE OF GENERAL SANTOS CITY'],
            ['name' => 'KING\'S COLLEGE OF MARBEL, INC.'],
            ['name' => 'MINDANAO POLYTECHNIC COLLEGE'],
            ['name' => 'MINDANAO STATE UNIVERSITY - GENERAL SANTOS CITY'],
            ['name' => 'NOTRE DAME OF DADIANGAS UNIVERSITY'],
            ['name' => 'NOTRE DAME OF MARBEL UNIVERSITY'],
            ['name' => 'SCHOLA DE SAN JOSE, INC.'],
            ['name' => 'RAMON MAGSAYSAY MEMORIAL COLLEGES'],
            ['name' => 'SANTA CRUZ MISSION SCHOOL, INC.'],
            ['name' => 'SOUTH COTABATO STATE COLLEGE'],
            ['name' => 'STI COLLEGE - GEN. SANTOS , INC'],
            ['name' => 'GREEN VALLEY COLLEGE FOUNDATION INCORPORATED'],
            ['name' => 'MARBEL SCHOOL OF SCIENCE AND TECHNOLOGY,INC.'],
            ['name' => 'AMA COMPUTER COLLEGE GENERAL SANTOS CITY'],
            ['name' => 'CENTRAL MINDANAO COLLEGES'],
            ['name' => 'REGENCY POLYTECHNIC COLLEGE, INC'],
            ['name' => 'COTABATO STATE UNIVERSITY'],
            ['name' => 'COTABATO FOUNDATION COLLEGE OF SCIENCE AND TECHNOLOGY'],
            ['name' => 'COTABATO MEDICAL FOUNDATION COLLEGE, INCORPORATED'],
            ['name' => 'DE LA VIDA COLLEGE, INCORPORATED'],
            ['name' => 'DR. DOMINGO B. TAMONDONG MEMORIAL HOSPITAL & COLLEGE FOUNDATION, INC.'],
            ['name' => 'DR. P. OCAMPO COLLEGES, INC.'],
            ['name' => 'HEADSTART COLLEGE OF COTABATO, INC.'],
            ['name' => 'KING\'S COLLEGE OF ISULAN'],
            ['name' => 'MINDANAO CAPITOL COLLEGES, INC.'],
            ['name' => 'UNIVERSITY OF SOUTHERN MINDANAO-KIDAPAWAN CITY CAMPUS'],
            ['name' => 'COLEGIO DE KIDAPAWAN'],
            ['name' => 'NOTRE DAME CENTER FOR CATECHESIS, INC.'],
            ['name' => 'NOTRE DAME HOSPITAL AND SIENA COLLEGE OF COTABATO, INC.'],
            ['name' => 'NOTRE DAME OF KIDAPAWAN COLLEGE'],
            ['name' => 'NOTRE DAME OF MIDSAYAP COLLEGE'],
            ['name' => 'NOTRE DAME OF SALAMAN COLLEGE'],
            ['name' => 'NOTRE DAME OF TACURONG COLLEGE'],
            ['name' => 'NOTRE DAME UNIVERSITY'],
            ['name' => 'QUEZON COLLEGES OF SOUTHERN PHILLIPINES, INC.'],
            ['name' => 'ST. BENEDICT COLLEGE OF COTABATO INC.'],
            ['name' => 'ST. LUKE\'S INSTITUTE, INCORPORATED'],
            ['name' => 'SENATOR NINOY AQUINO COLLEGE FOUNDATION, INC.'],
            ['name' => 'SHARIFF KABUNSUAN COLLEGE, INCORPORATED'],
            ['name' => 'SOUTHERN BAPTIST COLLEGE'],
            ['name' => 'SOUTHERN CHRISTIAN COLLEGE'],
            ['name' => 'SOUTHERN MINDANAO INSTITUTE OF TECHNOLOGY, INC.'],
            ['name' => 'SOUTHERN PHILIPPINES METHODIST COLLEGES, INC.'],
            ['name' => 'SULTAN KUDARAT EDUCATIONAL INSTITUTION'],
            ['name' => 'SULTAN KUDARAT STATE UNIVERSITY'],
            ['name' => 'UNIVERSITY OF SOUTHERN MINDANAO-MAIN'],
            ['name' => 'NORTH VALLEY COLLEGE FOUNDATION, INCORPORATED'],
            ['name' => 'STI COLLEGE COTABATO, INC.'],
            ['name' => 'STI COLLEGE KORONADAL CITY, INC.'],
            ['name' => 'I-LINK COLLEGE OF SCIENCE AND TECHNOLOGY INC.'],
            ['name' => 'COLAND SYSTEMS TECHNOLOGY, INCORPORATED'],
            ['name' => 'GOLDENSTATE COLLEGE OF KORONADAL CITY, INC.'],
            ['name' => 'MARVELOUS COLLEGE OF TECHNOLOGY, INC.'],
            ['name' => 'INTERNATIONAL CRUISE SHIP COLLEGE INCORPORATED'],
            ['name' => 'STI COLLEGE KORONADAL CITY, INC. TACURONG BRANCH'],
            ['name' => 'B.E.S.T. COLLEGE OF POLOMOLOK, INC.'],
            ['name' => 'RAMON MAGSAYSAY MEMORIAL COLLEGES-MARBEL, INC.'],
            ['name' => 'GENERAL SANTOS ACADEMY, INCORPORATED'],
            ['name' => 'MARBEL INSTITUTE OF TECHNICAL COLLEGE'],
            ['name' => 'JOJI ILAGAN INTERNATIONAL SCHOOL OF HOTEL AND TOURISM MANAGEMENT'],
            ['name' => 'MMG COLLEGE OF GENERAL SANTOS CITY, INC.'],
            ['name' => 'CRONASIA FOUNDATION COLLEGE, INC.'],
            ['name' => 'KIDAPAWAN DOCTORS COLLEGE, INCORPORATED'],
            ['name' => 'KULAMAN ACADEMY INC.'],
            ['name' => 'GENSAN COLLEGE OF TECHNOLOGY, INC.'],
            ['name' => 'PRIMASIA FOUNDATION COLLEGE, INC.'],
            ['name' => 'SOUTHPOINT COLLEGE OF ARTS AND TECHNOLOGY (SPAT), INC.'],
            ['name' => 'MAKILALA INSTITUTE OF SCIENCE AND TECHNOLOGY'],
            ['name' => 'WEST CELEBES COLLEGE OF TECHNOLOGY INCORPORATED'],
            ['name' => 'SOUTH CENTRAL MINDANAO COLLEGE OF SCIENCE AND TECHNOLOGY, INC.'],          
            ['name' => 'CENTRAL MINDANAO COMPUTER SCHOOL., INC.'],
            ['name' => 'ANTONIO R. PACHECO COLLEGE, INC.'],
            ['name' => 'AMA COMPUTER COLLEGE - COTABATO CAMPUS'],
            ['name' => 'ADVENTIST COLLEGE OF TECHNOLOGY, INCORPORATED'],
            ['name' => 'GOLDENSTATE COLLEGE'],
            ['name' => 'KUTAWATO DARUSSALAM COLLEGE, INC.'],
            ['name' => 'GENERAL SANTOS DOCTORS MEDICAL SCHOOL FOUNDATION, INC.'],
            ['name' => 'NOTRE DAME-SIENA COLLEGE OF POLOMOLOK'],
            ['name' => 'NOTRE DAME-RVM COLLEGE OF COTABATO'],
            ['name' => 'BROKENSHIRE COLLEGE SOCSKSARGEN, INC.'],
            ['name' => 'ACLC COLLEGE OF GENERAL SANTOS CITY, INC.'],
            ['name' => 'HOLY CHILD CENTRAL COLLEGES, INC'],
            ['name' => 'SOUTH EAST ASIAN INSTITUTE OF TECHNOLOGY, INC.'],
            ['name' => 'VMC ASIAN COLLEGE FOUNDATION, INC.'],
            ['name' => 'ASIAN COLLEGES AND TECHNOLOGICAL INSTITUTE, INC'],
            ['name' => 'STRATFORD INTERNATIONAL SCHOOL'],
            ['name' => 'ACLC COLLEGE OF MARBEL'],
            ['name' => 'KORBEL FOUNDATION COLLEGE, INC.'],
            ['name' => 'VILLAMOR COLLEGE OF BUSINESS AND ARTS'],
            ['name' => 'FILIPINO CANADIAN COMMUNITY COLLEGE FOUNDATION INCORPORATED '],
            ['name' => 'NEW ERA UNIVERSITY, GENERAL SANTOS CITY BRANCH'],
            ['name' => 'ACADEMIA DE TECNOLOGIA IN MINDANAO , INC.'],
            ['name' => 'JAMIAT COTABATO AND INSTITUTE OF TECHNOLOGY'],
            ['name' => 'SOUTHERN PHILIPPINE TECHNICAL COLLEGE OF KORONADAL, INCORPORATED'],
            ['name' => 'GOLDENSTATE COLLEGE OF KIAMBA, INC.'],
            ['name' => 'GOLDENSTATE COLLEGE OF MAASIM, INC.'],
            ['name' => 'GOLDENSTATE COLLEGE OF MALUNGON, INC.'],
            ['name' => 'NEW BRIGHTON SCHOOL OF THE PHILIPPINES, INC.'],
            ['name' => 'PACIFIC SOUTHBAY COLLEGE, INC.'],
            ['name' => 'GOODWILL COLLEGE OF NORTH EASTERN PHILIPPINES'],
            ['name' => 'VMC ASIAN COLLEGE OF PRESIDENT QUIRINO, INC.'],
            ['name' => 'SANTO NINO COLLEGE FOUNDATION, INC.'],
            ['name' => 'NEW HOPE SCHOOL OF AGRICULTURE AND FISHERY, INC.'],
            ['name' => 'ENVIROGREEN SCHOOL OF TECHNOLOGY'],
            ['name' => 'LEBAK FAMILY DOCTORS SCHOOL OF MIDWIFERY'],
            ['name' => 'KING SOLOMON INSTITUTE, INC.'],
            ['name' => 'GLAN INSTITUTE OF TECHNOLOGY'],
            ['name' => 'UST GENERAL SANTOS'],
            ['name' => 'SOUTH ASIATECH COLLEGE, INC.'],
            ['name' => 'NORTH CIRCLE ACADEMY, INC.'],
            ['name' => 'MALAPATAN COLLEGE OF SCIENCE AND TECHNOLOGY'],
            ['name' => 'COTABATO FOUNDATION COLLEGE OF SCIENCE AND TECHNOLOGY - ANTIPAS'],
            ['name' => 'COTABATO FOUNDATION COLLEGE OF SCIENCE AND TECHNOLOGY - DATU MONTAWAL'],
            ['name' => 'COTABATO FOUNDATION COLLEGE OF SCIENCE AND TECHNOLOGY - KATIPUNAN'],
            ['name' => 'COTABATO FOUNDATION COLLEGE OF SCIENCE AND TECHNOLOGY - PIKIT'],
            ['name' => 'SULTAN KUDARAT STATE UNIVERSITY - ISULAN'],
            ['name' => 'SULTAN KUDARAT STATE UNIVERSITY - LUTAYAN'],
            ['name' => 'SULTAN KUDARAT STATE UNIVERSITY - KALAMANSIG'],
            ['name' => 'SULTAN KUDARAT STATE UNIVERSITY - BAGUMBAYAN'],
            ['name' => 'SULTAN KUDARAT STATE UNIVERSITY - PALIMBANG'],
            ['name' => 'SULTAN KUDARAT STATE UNIVERSITY - TACURONG'],
            ['name' => 'UNIVERSITY OF SOUTHERN MINDANAO-ALAMADA CAMPUS'],
            ['name' => 'UNIVERSITY OF SOUTHERN MINDANAO-ALEOSAN CAMPUS'],
            ['name' => 'UNIVERSITY OF SOUTHERN MINDANAO-LIBUNGAN CAMPUS'],
            ['name' => 'OTHERS'],
        ];

        foreach ($schools as $s) {
            School::create($s);
        }
    }
}
